name: "Build and deploy"
on:
  push:
    branches:
      - "main"
permissions:
  packages: write
  contents: write

env:
  "IMAGE": "ghcr.io/${{ github.repository }}/tms-utbetalingsoversikt:${{ github.sha }}"
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Build application"
        run: "npm run build"
      - name: "Build and publish Docker image"
        run:
          "docker build --pull --tag ${IMAGE} . && echo $GITHUB_TOKEN | docker login\
          \ --username $GITHUB_REPOSITORY --password-stdin https://ghcr.io\
          \ && docker push ${IMAGE}"
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
  deploy:
    runs-on: "ubuntu-latest"
    needs: "build"
    strategy:
      matrix:
        cluster: [dev-gcp, prod-gcp]
    steps:
      - uses: "actions/checkout@v3"
      - name: "Deploy to ${{ matrix.cluster }}"
        uses: "nais/deploy/actions/deploy@v1"
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: nais/${{ matrix.cluster }}/nais.yaml
